=== rbirkby/mscui/Solutions/Main/Microsoft.Cui.SamplePages/Graphing/TimelineData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TimelineSampleData">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Scenario">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Section">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Row">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" minOccurs="0" name="Item">
                            <xs:complexType mixed="true">
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Units" type="xs:string" />
                                <xs:element minOccurs="0" name="UnitsDescription" type="xs:string" />
                                <xs:element minOccurs="0" name="YAxisMaxValue" type="xs:decimal" />
                                <xs:element minOccurs="0" name="YAxisMinValue" type="xs:decimal" />
                                <xs:element minOccurs="0" name="YAxisPadding" type="xs:decimal" />
                                <xs:element minOccurs="0" name="YAxisMajorInterval" type="xs:decimal" />
                                <xs:element minOccurs="0" name="YAxisIntervalMinimumHeight" type="xs:decimal" />
                                <xs:element minOccurs="0" name="Height" type="xs:decimal" />
                                <xs:element minOccurs="0" name="ShowNormalRange" type="xs:string" />
                                <xs:element minOccurs="0" name="NormalRangeDescription" type="xs:string" />
                                <xs:element minOccurs="0" name="NormalRangeMinimumValue" type="xs:decimal" />
                                <xs:element minOccurs="0" name="NormalRangeMaximumValue" type="xs:decimal" />
                                <xs:element minOccurs="0" name="NormalRangeBrush" type="xs:string" />
                                <xs:element minOccurs="0" name="HoverBackground" type="xs:string" />
                                <xs:element minOccurs="0" name="InterpolationLineColor" type="xs:string" />
                                <xs:element minOccurs="0" name="DataMarkerTemplate" type="xs:string" />
                                <xs:element minOccurs="0" name="PointTemplate" type="xs:string" />
                                <xs:element minOccurs="0" name="LabelTemplate" type="xs:string" />
                                <xs:element minOccurs="0" name="Style" type="xs:string" />
                                <xs:element minOccurs="0" name="Brand" type="xs:string" />
                                <xs:element minOccurs="0" name="FluidStrength" type="xs:string" />
                                <xs:element minOccurs="0" name="SolidStrength" type="xs:string" />
                                <xs:element minOccurs="0" name="Form" type="xs:string" />
                                <xs:element minOccurs="0" name="DoseLabel" type="xs:string" />
                                <xs:element minOccurs="0" name="Dose" type="xs:string" />
                                <xs:element minOccurs="0" name="DoseDuration" type="xs:string" />
                                <xs:element minOccurs="0" name="Route" type="xs:string" />
                                <xs:element minOccurs="0" name="Frequency" type="xs:string" />
                                <xs:element minOccurs="0" name="Comments" type="xs:string" />
                                <xs:element minOccurs="0" name="Clinician" type="xs:string" />
                                <xs:element minOccurs="0" name="Events">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="Event">
                                        <xs:complexType>
                                          <xs:sequence minOccurs="0">
                                            <xs:element name="Comments" type="xs:string" />
                                            <xs:element minOccurs="0" name="Clinician" type="xs:string" />
                                          </xs:sequence>
                                          <xs:attribute name="Type" type="xs:string" use="required" />
                                          <xs:attribute name="PlannedStartDate" type="xs:string" use="optional" />
                                          <xs:attribute name="PlannedEndDate" type="xs:string" use="optional" />
                                          <xs:attribute name="ActualStartDate" type="xs:string" use="optional" />
                                          <xs:attribute name="ActualEndDate" type="xs:string" use="optional" />
                                          <xs:attribute name="CanceledDate" type="xs:string" use="optional" />
                                          <xs:attribute name="Status" type="xs:string" use="optional" />
                                          <xs:attribute name="Y1" type="xs:decimal" use="optional" />
                                          <xs:attribute name="Y2" type="xs:decimal" use="optional" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="Name" type="xs:string" use="required" />
                              <xs:attribute name="Type" type="xs:string" use="optional" />
                              <xs:attribute name="StartDate" type="xs:string" use="optional" />
                              <xs:attribute name="EndDate" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:decimal" use="optional" />
                        <xs:attribute name="Name" type="xs:string" use="optional" />
                        <xs:attribute name="Description" type="xs:string" use="optional" />
                        <xs:attribute name="MaxLabelStackLevels" type="xs:decimal" use="optional" />
                        <xs:attribute name="ShowLabelOvercrowdingNotifications" type="xs:string" use="optional" />
                        <xs:attribute name="Background" type="xs:string" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="PatientId" type="xs:string" use="required" />
            <xs:attribute name="Description" type="xs:string" use="optional" />
            <xs:attribute name="BaseDate" type="xs:string" use="required" />
            <xs:attribute name="TimeFrequencySelectedIndex" type="xs:decimal" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rbirkby/mscui/Solutions/Main/Microsoft.Cui.SamplePages/Graphing/TimelineData.xml
<?xml version="1.0" encoding="utf-8"?>
<TimelineSampleData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TimelineData.xsd">
  <Scenario PatientId="1" Description="Secondary Care Data" BaseDate="18-Mar-2009 12:00:00" TimeFrequencySelectedIndex="9">
    <Section Name="Problems">
      <Row Id="91524294613" Name="diabetes mellitus type 1" Background="#F2F2F2">
        <Item Name="diabetes mellitus type 1" StartDate="14-Aug-1985 00:00:00"/>
      </Row>
      <Row Id="88246271609" Name="diabetic neuropathy" >
        <Item Name="diabetic neuropathy" StartDate="30-Sep-1995 00:00:00"/>
      </Row>
      <Row Id="19802752733" Name="alcoholic" Background="#F2F2F2">
        <Item Name="alcoholic" StartDate="14-Feb-2000 00:00:00"/>
      </Row>
      <Row Id="103716073035" Name="drowsy" MaxLabelStackLevels="2">
        <Item Name="drowsy" StartDate="16-Mar-2006 11:40:00" EndDate="16-Mar-2006 13:10:00"/>
        <Item Name="drowsy" StartDate="05-Jan-2008 11:50:00" EndDate="05-Jan-2008 13:10:00"/>
        <Item Name="drowsy" StartDate="16-Mar-2009 11:50:00" EndDate="16-Mar-2009 13:10:00"/>
      </Row>
      <Row Id="84977821110" Name="diabetic ketoacidosis" MaxLabelStackLevels="2" Background="#F2F2F2">
        <Item Name="diabetic ketoacidosis" StartDate="16-Mar-2006 12:00:00" EndDate="23-Mar-2006 23:59:00"/>
        <Item Name="diabetic ketoacidosis" StartDate="05-Jan-2008 12:10:00" EndDate="12-Jan-2008 23:59:00"/>
        <Item Name="diabetic ketoacidosis" StartDate="16-Mar-2009 12:10:00"/>
      </Row>
      <Row Id="35937449931" Name="infected foot : left" MaxLabelStackLevels="2">
        <Item Name="infected foot : left" StartDate="16-Mar-2006 12:00:00" EndDate="18-Mar-2006 09:35:00"/>
        <Item Name="infected foot : left" StartDate="05-Jan-2008 12:10:00" EndDate="07-Jan-2008 22:00:00"/>
        <Item Name="infected foot : left" StartDate="16-Mar-2009 12:10:00"/>
      </Row>
      <Row Id="17573944330" Name="urinary tract infection" MaxLabelStackLevels="2" Background="#F2F2F2">
        <Item Name="urinary tract infection" StartDate="16-Mar-2006 12:00:00" EndDate="23-Mar-2006 23:59:00"/>
        <Item Name="urinary tract infection" StartDate="05-Jan-2008 12:10:00" EndDate="12-Jan-2008 23:59:00"/>
        <Item Name="urinary tract infection" StartDate="16-Mar-2009 12:10:00"/>
      </Row>
      <Row Id="12868318557" Name="systemic sepsis">
        <Item Name="systemic sepsis" StartDate="18-Mar-2009 09:35:00"/>
      </Row>
      <Row />
    </Section>
    <Section Name="Medications">
      <Row Id="75123623608" Name="insulin" Description="— MIXTARD" MaxLabelStackLevels="3" Background="#F2F2F2">
        <Item Name="insulin" Type="SecondaryCareMedication" StartDate="30-Sep-1995 00:00:00" EndDate="16-Mar-2006 11:40:00">
          <Brand>MIXTARD</Brand>
          <Form>injection</Form>
          <DoseLabel>DOSE</DoseLabel>
          <Dose>variable</Dose>
          <Route>subcutaenous</Route>
          <Frequency>as required</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="30-Sep-1995 00:00:00" ActualEndDate="16-Mar-2006 11:40:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="insulin" Type="SecondaryCareMedication" StartDate="24-Mar-2006 00:00:00" EndDate="05-Jan-2008 11:40:00">
          <Brand>MIXTARD</Brand>
          <Form>injection</Form>
          <DoseLabel>DOSE</DoseLabel>
          <Dose>variable</Dose>
          <Route>subcutaenous</Route>
          <Frequency>as required</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="24-Mar-2006 00:00:00" ActualEndDate="05-Jan-2008 11:40:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="insulin" Type="SecondaryCareMedication" StartDate="13-Jan-2008 00:00:00" EndDate="16-Mar-2009 11:40:00">
          <Brand>MIXTARD</Brand>
          <Form>injection</Form>
          <DoseLabel>DOSE</DoseLabel>
          <Dose>variable</Dose>
          <Route>subcutaenous</Route>
          <Frequency>as required</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="13-Jan-2008 00:00:00" ActualEndDate="16-Mar-2009 11:40:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
      </Row>
      <Row Id="37692425250" Name="sodium chloride" Description=" 0.9%" MaxLabelStackLevels="3" ShowLabelOvercrowdingNotifications="True">
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="16-Mar-2006 11:40:00" EndDate="16-Mar-2006 12:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>1 L</Dose>
          <DoseDuration>over 30 minutes</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="16-Mar-2006 11:40:00" ActualEndDate="16-Mar-2006 12:10:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="16-Mar-2006 12:10:00" EndDate="16-Mar-2006 13:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>1 L</Dose>
          <DoseDuration>over 1 hour</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="16-Mar-2006 12:10:00" ActualEndDate="16-Mar-2006 13:10:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="16-Mar-2006 13:10:00" EndDate="16-Mar-2006 15:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>1 L</Dose>
          <DoseDuration>over 2 hours</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="16-Mar-2006 13:10:00" ActualEndDate="16-Mar-2006 15:10:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="16-Mar-2006 15:10:00" EndDate="23-Mar-2006 22:00:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>2 L</Dose>
          <DoseDuration>over 24 hours</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="16-Mar-2006 15:10:00" ActualEndDate="23-Mar-2006 22:00:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="05-Jan-2008 11:40:00" EndDate="05-Jan-2008 12:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>1 L </Dose>
          <DoseDuration>over 30 minutes</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="05-Jan-2008 11:40:00" ActualEndDate="05-Jan-2008 12:10:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="05-Jan-2008 12:10:00" EndDate="05-Jan-2008 13:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>1 L </Dose>
          <DoseDuration>over 1 hour</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="05-Jan-2008 12:10:00" ActualEndDate="05-Jan-2008 13:10:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="05-Jan-2008 13:10:00" EndDate="05-Jan-2008 15:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>1 L </Dose>
          <DoseDuration>over 2 hours</DoseDuration>
          <Route>intravenous</Route>
          <Frequency>once only</Frequency>
          <Events>
            <Event Type="administrations" ActualStartDate="05-Jan-2008 13:10:00" ActualEndDate="05-Jan-2008 15:10:00" Status="completed">
              <Comments></Comments>
              <Clinician></Clinician>
            </Event>
          </Events>
        </Item>
        <Item Name="sodium chloride" Type="SecondaryCareMedication" StartDate="05-Jan-2008 15:10:00" EndDate="12-Jan-2008 22:10:00">
          <FluidStrength>0.9%</FluidStrength>
          <Form>infusion</Form>
          <DoseLabel>VOLUME</DoseLabel>
          <Dose>2 L</Dose>
          <DoseDuration>over 24 hours</DoseDuration>
          <Route>intravenous</Route>
